version: '3.8'
services:
  api:
    build: .
    container_name: nexa-api
    restart: always
    ports:
      - "4000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nexa-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
